### ISSUE TITLE
Collision Failure between Dynamic and Static Entity

### ISSUE THREAD

**Issue by schecko** [xissburg/edyn#112]
I am attempting to build a basic 2D side scrolling platform game. Small disclaimer, this is my first time using a proper physics library but I wanted to try out enTT in my project, making Edyn a seemingly easy first choice to try out for physics.

I have a working example where collision occurs just fine: a dynamic box entity begins just above a static box entity and falls to the static entity, preventing the dynamic entity from moving further. The issue occurs when I add a single impulse at initialization of the dynamic entity, simulating a jump in the y axis. The impulse works as expected, however once the dynamic entity falls to the static entity, it falls through it. 

At first, I assumed this issue was caused by an incorrect/large step size. However in both cases with and without the impulse a contact is generated when the dynamic entity touches the static entity, leading me to believe something else is broken? The one difference I did find is that in the working case, two contacts events are produced but only one is triggered for the fail case. Any help would be appreciated.

Edyn Version: Latest Master/1.1.0

Code Snippet:
```
#include <entt/entt.hpp>
#include <edyn/edyn.hpp>

entt::registry reg;
entt::entity player;

void contact_started(entt::registry &registry, entt::entity entity)
{
	auto &manifold = registry.get<edyn::contact_manifold>(entity);
	float normal_impulse = 0;

	for (unsigned i = 0; i < manifold.num_points; ++i) {
		auto &cp = manifold.point[manifold.ids[i]];
		normal_impulse += cp.normal_impulse + cp.normal_restitution_impulse;
	}

	// Do something with `normal_impulse`, e.g. play sound.
}

void GameInitialize()
{
	edyn::init();
	edyn::attach(reg);

	edyn::on_contact_started(reg).connect<&contact_started>(reg);

	{
		auto def = edyn::rigidbody_def();
		def.kind = edyn::rigidbody_kind::rb_dynamic;
		def.position = {0.0f, 20.0f, 0.0f};
		// NOTE: toggle to see the issue
		if (1)
		{
			def.linvel = edyn::vector3_zero;
		}
		else
		{
			def.linvel = {0.0f, 50.0f, 0.0f};
		}
		def.shape = edyn::box_shape{0.5f, 0.2f, 0.4f};
		def.mass = 50.0f;
		def.update_inertia();
		def.material->restitution = 0.2f;
		def.material->friction = 0.9f;
		def.gravity = edyn::gravity_earth;

		player = reg.create();
		edyn::make_rigidbody(player, reg, def);
	}

	{
		auto def = edyn::rigidbody_def();
		def.kind = edyn::rigidbody_kind::rb_static;
		def.position = {0.0f, 0.0f, 0.0f};
		def.linvel = edyn::vector3_zero;
		def.shape = edyn::box_shape{10.5f, 1.0f, 0.4f};
		def.material->restitution = 0.2f;
		def.material->friction = 0.9f;

		auto ground = reg.create();
		edyn::make_rigidbody(ground, reg, def);
	}
}

void GameUpdate()
{
	edyn::update(reg);
}

void GameShutdown()
{
	edyn::detach(reg);
	edyn::deinit();
}

int main(int argc, char** argv)
{
	GameInitialize();
	for (;;)
	{
		GameUpdate();
	}
	GameShutdown();
}

```

**Comment by xissburg** [comment]
You’re setting an initial velocity of 50m/s upwards and when the dynamic box comes down and hits the static box, it has an even higher speed which is causing tunneling, i.e. it goes through the other object like a bullet. 

I have ran a simulation with your setup and the dynamic box lies inside the static box for one frame but due to its position within the box, it gets pushed to the other side because it’s closer to the bottom than to the top and the collision detection pushes objects towards the direction of minimum translation. Changing the fixed delta time from 16ms to 1ms prevented tunneling, though 1ms is kinda overkill for the fixed delta time, which translates to 1000 steps per second. 

The proper solution to this problem is continuous collision detection (CCD), which is not implemented yet. A time of impact must be calculated and the bodies must be interpolated backwards to that point in time before calculating the closest points.

**Comment by schecko** [comment]
I see. Thank you I'll try zooming in more to reduce the dependence on higher maximum speeds.
